[[language]]
name = "cpp"
language-servers = [
  "clangd",
]
[language-server.clangd]
command = "docker"
# We use 'exec -i' to pipe stdin/stdout into the container
args = [
  "exec",
  "-i",
  "vortex-container",  # Your container name
  "clangd",            # The command to run INSIDE the container
  
  # IMPORTANT: Map Host Path (Client) -> Container Path (Server)
  # IMPORTANT: Verify that the host mapping is correct, if the repo gets moved, this will not work
  "--path-mappings=/home/basil/scratchpad/vortex-container/container/vortex=/vortex",
  
  "--background-index",
  "--clang-tidy",
  "--header-insertion=iwyu",
  "--completion-style=detailed",
  "--function-arg-placeholders"
]
